countryInput      = css:input[placeholder='Select Country']
countryResults    = css:.ta-results
countrySuggestion = xpath:(//button[contains(@class,'ta-item')])[2]
placeOrder        = css:.action__submit
